### PR TITLE
Show SondeHub map in web interface

### PR DESCRIPTION
**Pull request by LukePrior**
This is intended as a replacement for the previous map shown on the web interface.

I need to do some final testing to ensure it zooms to latest sonde.

image
image

### CODE REVIEW

**Comment by LukePrior** [comment]
Ok this has been tested and is ready to go.

**Review by dl9rdz — COMMENTED** [review]
> String(sonde.config.sondehub.lat) != "null"
does not make much sense. lat is a char array, which always will convert into a String object (unless the device is out of memory, but then you are in trouble anyway...). Probably you wanted to check sonde.config.sondehub.lat[0] != 0.

In the long term, I'd like to slightly adjust this to have a global fixed position in the config that can be used for SondeHub and for the TTGO display (in case there is no GPS).

I am travelling the next week (let's hope everything goes well) so maybe will be rather inactive here until next Sunday.

**Comment by LukePrior** [comment]
> Probably you wanted to check sonde.config.sondehub.lat[0] != 0.

Ok I have updated it so it now just checks that the position is valid, as the default value is null this should work fine.

I have tested this and it works well.

**Comment by LukePrior** [comment]
> In the long term, I'd like to slightly adjust this to have a global fixed position in the config that can be used for SondeHub and for the TTGO display (in case there is no GPS).

That sounds like a good idea, it would also help in getting a distance measurement to sonde.

I note that @Benoit37000 appears to be working on this in their [branch](https://github.com/Benoit37000/rdz_ttgo_sonde)

**Pull request merged**
