### PR TITLE
log GPS, PMU, Spectrum peak, and Scanner via MQTT

### PR DESCRIPTION
**Pull request by ckuethe**
The aim is to be very similar to what's on the display, but for remote deployments. Messages can be controlled by OR-ing values together in the mqtt_active config element.

* sondes = 0x01
* uptime = 0x02
* pmu = 0x04
* gps = 0x08
* RF info (scanner and spectrum) = 0x10
* generic debug = 0x80

Using a value of 1 will send only sonde measurements over MQTT since they are most interesting; a value of 3 replicates the current behavior sending both uptime and sondes. There is also a control adjust the reporting rate of uptime, PMU, and gps messages.

PMU messages use positive current to indicate battery charging and negative current to indicate discharging. GPS messages include both host and GPS time, and fix state, without regard to fixed position.

`cfg.js` has been updated to add the new controls, and version.h updates the filesystem minor version to reflect that change

Future improvements may include:
* hoisting the time formatter to make it useful for all other time printers
* TLS support
* remote control over MQTT
* reporting position source in the uptime message (fixed or gps)
* replacing Serial.print and .println with .printf or LOG_x

### CODE REVIEW

**Comment by ckuethe** [comment]
Rebased

**Comment by dl9rdz** [comment]
no need to change the minor FS version, as there are no relevant changes.... Changed the logging to the LOG_x macros as well.

**Comment by ckuethe** [comment]
ok, I wasn't sure if the FS version needed to change because I was updating the html/js.

can I get write access to the wiki so I can document my changes?

**Comment by dl9rdz** [comment]
Hi, Usually I have been doing this as described here:
https://github.com/dl9rdz/rdz_ttgo_sonde/wiki/NFAQ-%28Not-Frequently-Asked-Questions%29

**Comment by ckuethe** [comment]
@dl9rdz  https://github.com/ckuethe/rdzsonde_wiki/commit/4db8b58ebd7701a02c56b8ba54af2883c0d6ff1e

**Pull request merged**
