### PR TITLE
Temperature and humidity for RS41

### PR DESCRIPTION
**Pull request by mycarda**
Temperature and humidity for RS41

These variables added and populated with the values
sonde.si().temperature
sonde.si().tempRHSensor
sonde.si().relativeHumidity

The values are printed to Serial when they are updated but not used anywhere. They could be displayed but as I am not familiar with the code for the display, I have left this to someone else. I am interested in passing these values in mqtt and I will add something for that later.

The temperature and relative humidity values have been compared to those seen on radiosonde.info and those produced by Radiosonde Auto-RX during live telemetry. The values agree to a decimal place (as far as I can tell). 
Here is how it works
To calculate the temperature and humidity, the calibration values from the subframe in the 79-STATUS block are required.
This update takes the subframe number [0x17] and subframe data [0x18] from the 79-STATUS block and adds this to a 51x16 subframe data structure (calibration.value in RS41.cpp). It's based on https://github.com/einergehtnochrein/ra-firmware and zilog80's code. Once all 51 items are received, not only do you have the calibration values you need for the temperature and humidty, but you can read a lot of other information from the data structure, for example,  
calibration.value.firmwareVersion and 
calibration.value.intTemperatureCpu etc.
There were several open source calculations for the temperature and humidty but I chose the ones used by https://github.com/einergehtnochrein/ra-firmware (very similar to the advanced ones used by zilog80). This was the easiest (for me) to understand and used most of the calibration values (even though some of these values alwasys seem to be zero).

### CODE REVIEW

**Comment by eben80** [comment]
Is air-pressure a lot more work to implement?

**Comment by dl9rdz** [comment]
Implementing is not that much of a problem. Some checks if its really a RS41-SGP (with pressure sensor), and then a bit of math. A bit more than for temp/hum.

The main problem is space on the TTGO. Its now aprox. 98% full.  So before adding a lot of new features, one should think about how to handle this in the future. Either conditional compiles with different subsets of features, or getting rid of OTA (or do smarter OTA with a tiny "upgrade" image and larger "fully functional" image.)

**Comment by eben80** [comment]
> Implementing is not that much of a problem. Some checks if its really a RS41-SGP (with pressure sensor), and then a bit of math. A bit more than for temp/hum.
> 
> The main problem is space on the TTGO. Its now aprox. 98% full. So before adding a lot of new features, one should think about how to handle this in the future. Either conditional compiles with different subsets of features, or getting rid of OTA (or do smarter OTA with a tiny "upgrade" image and larger "fully functional" image.)

Yes currently I'm doing away with the OTA partitioning and I'm sitting at 61% with this commit included as well.
I can understand its a balance between having all the features and keeping it OTA upgradable.

image

**Comment by dl9rdz** [comment]
So I have merged that pull request but made some changes. Thanks for your contribution!

What I disliked a bit is the fact that a single global data structure was used for the calibration data. If someone is receiving multiple sondes on multiple frequencies (either by manually switching or by modifying screens to do so automatically each X seconds), calibration data of multiple sondes are mixed up. So instead, I moved the calibration to a per-frequency "extra" item in sonde data. This is allocated on demand, so memory is used only for frequencies on which RS41 sondes have been received.  The current code probably should still be enhanced such that the ID on a single frequency changes, the calibration data should be cleared (TODO). 

I also tried to minimize memory usage (e.g., using a utin64_t bitfield for checking calibration validity instead of an 64 byte array)

I have not yet tested this code, so bugs are possible.

**Comment by mycarda** [comment]
> What I disliked a bit is the fact that a single global data structure was used for the calibration data. If someone is receiving multiple sondes on multiple frequencies (either by manually switching or by modifying screens to do so automatically each X seconds), calibration data of multiple sondes are mixed up. So instead, I moved the calibration to a per-frequency "extra" item in sonde data. This is allocated on demand, so memory is used only for frequencies on which RS41 sondes have been received. 

Excellent point! I had not considered that and your solution to allocate on-demand is good.

> I also tried to minimize memory usage (e.g., using a utin64_t bitfield for checking calibration validity instead of an 64 byte array)

Yes, this is also better than what I coded.

> I have not yet tested this code, so bugs are possible.

I have not had chance to look at this project for a while but I thought it was about time I updated my device to the latest development code. I have one device running on my original code and one on your improved code. The temperature and humidity values are identical so, at least for receiving a single radiosonde, your improvements are good. As I have never managed to receive more than one radiosonde at the same time, I cannot test what happens when you switch between two frequencies.

Where you have left my old code in "#if 0" to comment it out (for example RS41.cpp line 767), I think it's pretty save to remove my code as yours works better.

Thanks for improving my attempt at temperature and humidity.

**Pull request merged**
