### PR TITLE
Integrate platformio without breaking changes

### LINKED ISSUE #35: Platformio integration
I think it would be beneficial for project to use Platformio to handle all dependencies and deployment.

(I'll make pull request once it will be done)

### PR DESCRIPTION
**Pull request by analogic**
Fixes #35 I've tried to make minimal changes as possible

### CODE REVIEW

**Comment by analogic** [comment]
Hmmm where do "WStype_t" come from?

**Comment by dl9rdz** [comment]
> Hmmm where do "WStype_t" come from?

That is from Arduino//libraries//WebSockets/src/WebSockets.h
But currently not in use (just a function surrounded with #if 0 in RX_FSK.ino is using that type).

**Comment by dl9rdz** [comment]
I merged your pull request and removed the WebSocket.h, because it also caused a compile error with platform.io (missing dependency WiFiClientSecure.h). Compiles fine with pio and arduino IDE. Thanks for your contribution.

**Comment by dl9rdz** [comment]
Just another minor question: I guess this addition to RX_FSK.ino is not really necessary?
```
#ifdef TTGO_V2
// platformio currently fails to build with board v2 so ve override v1 pins instead
#define OLED_SDA 4
#define OLED_SCL 15
#define OLED_RST 16
#endif
```
My code does not use these platform specific constant definitions, as the binary image is supposed to run on any board. By default, it does some autodetection and autoconfiguration of pins, or alternatively uses pin definitions stored in a file on the flash file system (modifiable via web interface).

**Comment by analogic** [comment]
Aha! In that case you can safely remove that. I am not completely familiar with your code yet and was trying workaround https://github.com/platformio/platform-espressif32/issues/344

(In upcoming days I will try to add MQTT #11 as I am also interested in this feature)

**Pull request closed without merging**
