### PR TITLE
INCOMPLETE: Dark mode choice with persistence

### PR DESCRIPTION
**Pull request by eben80**
OK this is how far I got.  I have problems getting the CSS priority right when system pref is light mode. 

Maybe someone else can find and fix my mistakes?

I've kind of hit the wall of my abilities. 😢

### CODE REVIEW

**Comment by LukePrior** [comment]
Maybe this could be of help?

https://stackoverflow.com/questions/56300132/how-to-override-css-prefers-color-scheme-setting

**Comment by dl9rdz** [comment]
I unfortunately will not have time available for checking this myself this year.... too busy with moving....
Let me know when you think it is complete/good enough, I will be happy to merge it to the devel build.

**Comment by LukePrior** [comment]
I would add the map selector thing you added to your simulator here also.

**Comment by eben80** [comment]
Totally understand.. It's the silly season time of the year.
I will try and update this PR once I find how to make it behave as intended
and with that selector function.

**Pull request closed without merging**
